#region Copyright Syncfusion Inc. 2001-2015.
// Copyright Syncfusion Inc. 2001-2015. All rights reserved.
// Use of this code is subject to the terms of our license.
// A copy of the current license can be obtained at any time by e-mailing
// licensing@syncfusion.com. Any infringement will be prosecuted under
// applicable laws. 
#endregion
#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SampleBrowser.Droid.Resource", IsApplication=true)]

namespace SampleBrowser.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::SampleBrowser.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::SampleBrowser.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int About = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AppIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Apply = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Controls = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Setting = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000d
			public const int action_settings = 2131230733;
			
			// aapt resource value: 0x7f080006
			public const int axisLayout = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int chartAreaLayout = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int chartTitle = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int dataMarkerLayout = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int gridLineLayout = 2131230723;
			
			// aapt resource value: 0x7f08000b
			public const int iconView = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int label = 2131230732;
			
			// aapt resource value: 0x7f080008
			public const int legendHeader = 2131230728;
			
			// aapt resource value: 0x7f08000a
			public const int legendItemsLayout = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int legendScrollView = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int legendViewGroup = 2131230727;
			
			// aapt resource value: 0x7f080000
			public const int rootLayout = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int seriesLayout = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int chart_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int chart_legend = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int chart_legend_item = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int menu_main = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int action_settings = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int hello_world = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int title_activity_main = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
