#region Copyright Syncfusion Inc. 2001-2015.
// Copyright Syncfusion Inc. 2001-2015. All rights reserved.
// Use of this code is subject to the terms of our license.
// A copy of the current license can be obtained at any time by e-mailing
// licensing@syncfusion.com. Any infringement will be prosecuted under
// applicable laws. 
#endregion
#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SampleBrowser.Resource", IsApplication=true)]

namespace SampleBrowser
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Syncfusion.Linq.Android.Resource.String.library_name = global::SampleBrowser.Resource.String.library_name;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Ascending = global::SampleBrowser.Resource.Drawable.Ascending;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Descending = global::SampleBrowser.Resource.Drawable.Descending;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Sort = global::SampleBrowser.Resource.Drawable.Sort;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.SortDescending = global::SampleBrowser.Resource.Drawable.SortDescending;
			global::Syncfusion.SfDataGrid.Android.Resource.String.library_name = global::SampleBrowser.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide2 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slideleft = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slideright = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int column_array = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int condition_array = 2131230721;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int white = 2131165184;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Ascending = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int austria = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int autocomplete = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int belgium = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int busy = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int cambodia = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int canada = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int chart = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int close = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int datagrid = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int denmark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Descending = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int digital = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int divider_gradient = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ecuador = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int egypt = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int finland = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int france = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int gauge = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int germany = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int greece = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int guyana = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int hongkong = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int hungary = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int icon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Image0 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Image1 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Image10 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Image11 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Image12 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Image13 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Image14 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Image15 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Image16 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Image17 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int Image18 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int Image19 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int Image2 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int Image20 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Image21 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Image22 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Image23 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Image24 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Image25 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Image26 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Image27 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Image28 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int Image3 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int Image4 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int Image5 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int Image6 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int Image7 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int Image8 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int Image9 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int india = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int indonesia = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ireland = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int italy = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int jamaica = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int jordan = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int kenya = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int libya = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int linear = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int listpopup = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int luxembourg = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int madagascar = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int malaysia = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int menu = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int mexico = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int mount = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int namibia = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int netherlands = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int norway = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int oman = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int peru = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int poland = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int portugal = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int qatar = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int range = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int RedDown = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int russia = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int saudiarabia = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int settings = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int singapore = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int Sort = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int SortDescending = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int SortingDown = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int SortingUp = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int spain = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int sweden = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int thailand = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int tick = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int treemap = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int turkey = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int uae = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int ukraine = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int unitedkingdom = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int unitedstates = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int uruguay = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int vietnam = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int wakeland = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int yemen = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int zambia = 2130837606;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0002
			public const int Itemname = 2131361794;
			
			// aapt resource value: 0x7f0a0011
			public const int background = 2131361809;
			
			// aapt resource value: 0x7f0a0004
			public const int eightsegment = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int fourteensegment = 2131361797;
			
			// aapt resource value: 0x7f0a0007
			public const int fragment_content = 2131361799;
			
			// aapt resource value: 0x7f0a0001
			public const int icon = 2131361793;
			
			// aapt resource value: 0x7f0a000d
			public const int imageButton = 2131361805;
			
			// aapt resource value: 0x7f0a0009
			public const int img = 2131361801;
			
			// aapt resource value: 0x7f0a0013
			public const int labelLayout = 2131361811;
			
			// aapt resource value: 0x7f0a0012
			public const int layout = 2131361810;
			
			// aapt resource value: 0x7f0a0010
			public const int list = 2131361808;
			
			// aapt resource value: 0x7f0a0000
			public const int rootLayout = 2131361792;
			
			// aapt resource value: 0x7f0a000f
			public const int samplearea = 2131361807;
			
			// aapt resource value: 0x7f0a000e
			public const int settings = 2131361806;
			
			// aapt resource value: 0x7f0a0003
			public const int sevensegment = 2131361795;
			
			// aapt resource value: 0x7f0a0006
			public const int sixteensegment = 2131361798;
			
			// aapt resource value: 0x7f0a0008
			public const int tabRow = 2131361800;
			
			// aapt resource value: 0x7f0a000b
			public const int tagtxt = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int title_text = 2131361804;
			
			// aapt resource value: 0x7f0a000a
			public const int txt = 2131361802;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int aboutpage = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int circulargauge_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int customizedview = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int digitalgauge_layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int listitem_layout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int property_header = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int samplelist_layout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SamplePage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int sfautocomplete_layout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int sfbusyindicator_layout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int sfrangeslider_layout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int showcase_layout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int treemap_layout = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int blueStyle = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int choose_column = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int choose_condition = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int darkStyle = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int defaultStyle = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int filter_text = 2131099652;
			
			// aapt resource value: 0x7f06000b
			public const int greenStyle = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int library_name = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int redStyle = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int support = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int website = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090001
			public const int MyTheme_ActionBar_TabBar = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int MyTheme_ActionBar_TabText = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int MyTheme_ActionBar_TabView = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int PropertyApp = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int samplelist = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
